# Generated by Django 4.2.7 on 2023-12-06 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('document_id', models.CharField(max_length=15, unique=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Anfitrion',
        ),
        migrations.DeleteModel(
            name='Huesped',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
