# Generated by Django 4.2.7 on 2023-12-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_perfil_remove_huesped_usuario_delete_anfitrion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='numero_cuenta',
        ),
    ]
