# Generated by Django 4.2.7 on 2023-12-11 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_reserva_costo_total_reserva_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='propriedad',
            new_name='propiedad',
        ),
    ]
