# Generated by Django 4.2.7 on 2023-12-09 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propiedad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='capacidad',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tarifa',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='ubicacion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
