# Generated by Django 4.2.7 on 2023-12-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0002_propiedad_capacidad_propiedad_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='descricion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='invitados_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='numero_banos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='numero_habitaciones',
            field=models.IntegerField(default=1),
        ),
    ]
