# Generated by Django 4.2.7 on 2023-12-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_remove_servicio_propiedad'),
        ('propiedad', '0003_propiedad_descricion_propiedad_extra_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='servicios',
            field=models.ManyToManyField(to='servicios.servicio'),
        ),
    ]
