# Generated by Django 4.2.7 on 2023-12-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_rename_descricion_servicio_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='propiedad',
        ),
    ]
